"""Tests for tools/sync_cron.py — the config.yml -> cron line generator."""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
sys.path.insert(0, str(ROOT))

import sync_cron  # noqa: E402

YEAR = 2026


def utc_hours(tz: str, hour: int) -> set[tuple[int, int]]:
    return {(h, m) for h, m, _ in sync_cron.utc_slots(tz, hour, YEAR)}


def test_dst_zone_emits_one_line_per_season():
    # 19:00 New York is 23:00 UTC in EDT and 00:00 UTC in EST.
    assert utc_hours("America/New_York", 19) == {(23, 0), (0, 0)}


def test_fixed_offset_zone_emits_a_single_line():
    # Asia/Tokyo has no daylight saving, so one cron covers the year.
    assert utc_hours("Asia/Tokyo", 8) == {(23, 0)}


def test_half_hour_offset_keeps_its_minutes():
    # India is UTC+5:30 — dropping the minutes would nag half an hour early.
    # 09:00 IST is 03:30 UTC, so the cron must be "30 3 * * *".
    assert utc_hours("Asia/Kolkata", 9) == {(3, 30)}


def test_utc_itself_round_trips():
    assert utc_hours("UTC", 19) == {(19, 0)}


def test_southern_hemisphere_dst_also_yields_two():
    assert len(utc_hours("Australia/Sydney", 19)) == 2


@pytest.mark.parametrize("hour", range(0, 24, 4))
def test_every_slot_really_maps_back_to_nag_hour(hour):
    """The generated UTC times must actually be `hour` local time."""
    tz = ZoneInfo("America/New_York")
    for h, m, _ in sync_cron.utc_slots("America/New_York", hour, YEAR):
        # Check the slot against both seasons; it must be right in one of them.
        locals_ = []
        for month in (1, 7):
            utc = datetime(YEAR, month, 15, h, m, tzinfo=timezone.utc)
            locals_.append(utc.astimezone(tz).hour)
        assert hour in locals_, f"{h:02d}:{m:02d}Z never lands at {hour}:00 local"


def test_midnight_local_does_not_break():
    slots = sync_cron.utc_slots("America/New_York", 0, YEAR)
    assert 1 <= len(slots) <= 2


def test_block_renders_valid_cron_syntax():
    block = sync_cron.cron_block("America/New_York", 19, YEAR)
    crons = [ln for ln in block.splitlines() if "- cron:" in ln]
    assert len(crons) == 2
    for line in crons:
        expr = line.split('"')[1]
        minute, hour, dom, month, dow = expr.split()
        assert 0 <= int(minute) <= 59 and 0 <= int(hour) <= 23
        assert (dom, month, dow) == ("*", "*", "*")


def test_render_replaces_the_block_in_place():
    text = (
        "on:\n"
        "  # Generated by tools/sync_cron.py — do not hand-edit.\n"
        "  schedule:\n"
        '    - cron: "0 5 * * *"\n'
        "  workflow_dispatch:\n"
    )
    out = sync_cron.render(text, '  schedule:\n    - cron: "0 9 * * *"\n')
    assert '- cron: "0 9 * * *"' in out
    assert '- cron: "0 5 * * *"' not in out
    # Everything after the block must survive untouched.
    assert out.endswith("  workflow_dispatch:\n")
    assert out.startswith("on:\n")


def test_render_refuses_a_workflow_with_no_schedule():
    with pytest.raises(SystemExit):
        sync_cron.render("on:\n  workflow_dispatch:\n", "  schedule:\n")


def test_committed_workflow_is_in_sync_with_config():
    """Guards against editing config.yml and forgetting to re-run the script."""
    from nagger.config import load_config

    cfg = load_config(ROOT / "config.yml")
    year = datetime.now(timezone.utc).year
    block = sync_cron.cron_block(cfg.schedule.timezone, cfg.schedule.nag_hour, year)
    text = sync_cron.WORKFLOW_PATH.read_text(encoding="utf-8")
    assert sync_cron.render(text, block) == text, (
        "nag.yml is stale — run `python tools/sync_cron.py`"
    )
