"""Rewrite the workflow's cron lines to match `schedule:` in config.yml.

    python tools/sync_cron.py            # update .github/workflows/nag.yml
    python tools/sync_cron.py --check    # exit 1 if it's out of date
    python tools/sync_cron.py --print    # just show the lines

GitHub Actions cron is UTC-only and ignores daylight saving, so a single cron
line can only be right for half the year. This emits one line per UTC offset
your timezone uses — usually two, one per DST season — and the gate step in
the workflow drops whichever run is in the wrong season.

Run it after changing `nag_hour` or `timezone`; you never have to work out the
UTC hour yourself.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from nagger.config import ConfigError, load_config  # noqa: E402

WORKFLOW_PATH = ROOT / ".github" / "workflows" / "nag.yml"

# Local times that don't exist (the hour a spring-forward skips) still yield a
# UTC instant, which would add a bogus cron line. Real seasons last months, so
# anything covering less than a week of the year is one of those artefacts.
MIN_DAYS = 7


def utc_slots(tz_name: str, nag_hour: int, year: int) -> list[tuple[int, int, str]]:
    """UTC (hour, minute, label) pairs that hit `nag_hour` local time in `year`.

    One entry per offset the zone uses. Minutes matter: India is UTC+5:30 and
    Lord Howe shifts by 30 minutes rather than an hour.
    """
    tz = ZoneInfo(tz_name)
    counts: Counter[tuple[int, int, str]] = Counter()
    day = date(year, 1, 1)
    while day.year == year:
        local = datetime(day.year, day.month, day.day, nag_hour, tzinfo=tz)
        utc = local.astimezone(timezone.utc)
        counts[(utc.hour, utc.minute, local.tzname() or tz_name)] += 1
        day += timedelta(days=1)

    slots = [slot for slot, days in counts.items() if days >= MIN_DAYS]
    # A zone whose every reading looked like an artefact still needs a cron.
    return sorted(slots or [max(counts, key=counts.get)])


def cron_block(tz_name: str, nag_hour: int, year: int) -> str:
    slots = utc_slots(tz_name, nag_hour, year)
    lines = [
        "  # Generated by tools/sync_cron.py — do not hand-edit.",
        f"  # {nag_hour:02d}:00 {tz_name}, as UTC. Re-run that script after changing",
        "  # `nag_hour` or `timezone` in config.yml. The gate step below skips",
        "  # whichever line is in the wrong daylight-saving season.",
        "  schedule:",
    ]
    for hour, minute, label in slots:
        lines.append(
            f'    - cron: "{minute} {hour} * * *" # {nag_hour:02d}:00 {label}'
        )
    return "\n".join(lines) + "\n"


# Matches the schedule: key plus the generated comments above it and every
# cron/comment line under it, stopping at the next top-level `on:` key.
BLOCK_RE = re.compile(
    r"(?:^[ \t]*#.*\n)*^[ \t]*schedule:[ \t]*\n(?:^[ \t]*(?:-[ \t]*cron:|#).*\n)*",
    re.MULTILINE,
)


def render(text: str, block: str) -> str:
    if not BLOCK_RE.search(text):
        raise SystemExit(
            f"Couldn't find a `schedule:` block in {WORKFLOW_PATH.name}. If you "
            "removed it, add `  schedule:` back under `on:` and re-run."
        )
    return BLOCK_RE.sub(lambda _: block, text, count=1)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="don't write; exit 1 if the workflow is stale")
    parser.add_argument("--print", dest="show", action="store_true",
                        help="print the cron block and exit")
    parser.add_argument("--year", type=int, default=None,
                        help="year whose DST rules to use (default: current)")
    parser.add_argument("--config", type=Path, default=None,
                        help="path to config.yml (default: repo root)")
    args = parser.parse_args()

    try:
        cfg = load_config(args.config)
    except ConfigError as exc:
        print(f"config.yml {exc}", file=sys.stderr)
        return 1

    year = args.year or datetime.now(timezone.utc).year
    block = cron_block(cfg.schedule.timezone, cfg.schedule.nag_hour, year)

    if args.show:
        print(block, end="")
        return 0

    text = WORKFLOW_PATH.read_text(encoding="utf-8")
    updated = render(text, block)

    if args.check:
        if updated != text:
            print(f"{WORKFLOW_PATH.name} is out of date — run tools/sync_cron.py",
                  file=sys.stderr)
            return 1
        print(f"{WORKFLOW_PATH.name} is up to date.")
        return 0

    print(f"config.yml: {cfg.schedule.nag_hour:02d}:00 {cfg.schedule.timezone}")
    if updated == text:
        print(f"{WORKFLOW_PATH.name} already matches — nothing to do.")
        return 0
    WORKFLOW_PATH.write_text(updated, encoding="utf-8", newline="\n")
    count = block.count("- cron:")
    print(f"Wrote {count} cron line{'s' if count != 1 else ''} to {WORKFLOW_PATH.name}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
